integrations/urls.py
from django.urls import path

from .views import list_results, healthcheck

app_name = 'api'

urlpatterns = [
    path("hooks/handler_results", list_results),
    path("hooks/get_status", healthcheck)
]

testruns/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'test-runs'

urlpatterns = [
    path('', DroneCIRunListIndex.as_view(), name='all_runs'),
]

trinity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tests.urls', namespace='tests')),
    path('api/', include('integrations.urls', namespace='api')),
    path('test-run/', include('testruns.urls', namespace='test-runs'))
]

integrations/models.py
from django.db import models


class TestRunResults(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=True)
    body_test = models.JSONField(null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body_test)


class DroneCIListResults(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=True)
    number = models.CharField(max_length=255, verbose_name='Номер билда')
    status = models.CharField(max_length=255, verbose_name='Статус')
    autor_build = models.CharField(max_length=255, verbose_name='Автор запуска')
    date_run = models.DateTimeField(verbose_name='Дата запуска')

    def __str__(self):
        return str(self.number)

    def get_link_in_drone(self):
        return f'https://ci.idwell.tech/iDWELL/idwell-ui-tests/{self.id}'

testruns/models.py
from django.db import models

# Create your models here.

integrations/views.py
import json

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from integrations.serializers import TestRunSerializer, DroneCIResultsSerializer


@api_view(['GET'])
def healthcheck(request):
    if request.method == 'GET':
        return Response("Connection successful", status=status.HTTP_200_OK)
    return Response(status=status.is_server_error)



@api_view(['POST'])
def list_results(request):
    if request.method == 'POST':
        result = {'body_test': request.data}
        serializer = TestRunSerializer(data=result)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# def droneci_list_results(request):
#     if request.method == 'GET':
#         result = {'drone_results': request.data}
#         serializer = DroneCIResultsSerializer(data=result)
#         if serializer.is_valid():
#             DroneCIListResults.objects.all().delete()
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)





# @api_view(['GET', 'POST'])
# def snippet_list(request):
#     if request.method == 'GET':
#         test_runs = DroneResultModel.objects.all()
#         serializer = DroneSerializer(test_runs, many=True)
#         return Response(serializer.data)
#
#     elif request.method == 'POST':
#         serializer = DroneSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# @api_view(['POST'])
# def list_results(request):
#     if request.method == 'POST':
#         for d in request.data["results"]:
#             serializer = DroneSerializer(data=json.loads(d))
#             if serializer.is_valid():
#                 serializer.save()
#         return Response(serializer.errors, status=status.HTTP_201_CREATED)
#         raise Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

testruns/views.py
from django.views.generic import ListView
from testruns.droneci_script import update_runs
from integrations.models import DroneCIListResults


class DroneCIRunListIndex(ListView):
    model = DroneCIListResults
    template_name = 'testruns/index.html'
    context_object_name = 'runs_list'
    paginate_by = 10

    def get_last_runs(self):
        data = update_runs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update_data'] = self.get_last_runs
        return context

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Trinity</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>

<body>
    <main class="main">
        {% include 'sidebar_2.html' %}

          <section class="content">
        {% block content %}
        {% endblock %}

    </section>
    </main>

    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/comment2.html
<section>
  <div class="container my-5 py-5">
    <h3 class="title-comments">Комментарии ({{ comments.count }})</h3>
    <div class="row d-flex justify-content-center">

        <div class="card">


    {% for comment in comments %}
          <div class="card-body border-bottom"">
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://avatars.githubusercontent.com/u/45531331?s=40&v=4" alt="avatar" width="40" height="40" />
              <div>
                <h6 class="fw-bold small mb-1">{{ comment.author.username }}</h6>
                <p class="text-muted small mb-0">{{ comment.created }}</p>
              </div>
            </div>

            <p class="mt-3 mb-4 pb-2">{{ comment.text }}</p>
          </div>

          {% endfor %}



          <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://avatars.githubusercontent.com/u/45531331?s=40&v=4" alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                <textarea class="form-control" id="textAreaExample" rows="4"
                  style="background: #fff;"></textarea>
              </div>
            </div>
            <div class="float-end mt-2 pt-1">
              <button type="button" class="btn btn-primary btn-sm">Опубликовать</button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

templates/comments.html
{% load static %}

<div class="comments">
<h3 class="title-comments">Комментарии ({{ comments.count }})</h3>
<ul class="media-list">
  {% for comment in comments %}
          <div class="card-body">
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://avatars.githubusercontent.com/u/45531331?s=40&v=4" alt="avatar" width="60"
                height="60" />
              <div>
                <h6 class="fw-bold text-primary mb-1">{{ comment.author.username }}</h6>
                <p class="text-muted small mb-0">{{ comment.created }}</p>
              </div>
            </div>

            <p class="mt-3 mb-4 pb-2">{{ comment.text }}</p>
          </div>

          {% endfor %}

   <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://avatars.githubusercontent.com/u/45531331?s=40&v=4" alt="avatar" width="40"
                height="40" />
              <div class="form-outline w-100">
                <textarea class="form-control" id="textAreaExample" rows="4"
                  style="background: #fff;"></textarea>
              </div>
            </div>
            <div class="float-end mt-2 pt-1">
              <button type="button" class="btn btn-primary btn-sm">Опубликовать</button>
            </div>
          </div>


</ul>
</div>

templates/filters.html
<nav class="navbar">
  <div class="container-fluid">

      <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Поиск по сценариям" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>


      <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary">Автоматизирован</button>
          <button type="button" class="btn btn-outline-primary">Не автоматизирован</button>
          <button type="button" class="btn btn-outline-primary">Пропущен</button>
      </div>

  </div>
</nav>

templates/messages.html
{% if messages %}
    {% for message in messages %}

<div class="alert {{ message.tags }}" id="msg" role="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="d-flex">
    <div class="toast-body">
    Hello, world! This is a toast message.
   </div>
    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>


    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#">Trinity</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/sidebar_2.html
{% load static %}

<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark sidebar_2" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <img src="{% static 'img/logo.png' %}" class="bi me-2"  width="40" height="32">
      <span class="fs-4">Trinity</span>
    </a>
    <hr>

        <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'tests:all_scenario' %}" class="nav-link" aria-current="page">
            <img src="{% static 'img/scenario.svg' %}" class="menu__element-title-icon" width="16" height="16">
          Все сценарии
        </a>
      </li>
      <li>
        <a href="{% url 'test-runs:all_runs' %}" class="nav-link text-white">
           <img src="{% static 'img/clipboard-data.svg' %}" class="menu__element-title-icon" width="16" height="16">
          Все запуски
        </a>
      </li>
    </ul>


    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://avatars.githubusercontent.com/u/45531331?s=40&v=4" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>AAliamkina</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">Новый проект</a></li>
        <li><a class="dropdown-item" href="#">Настройки</a></li>
        <li><a class="dropdown-item" href="#">Профиль</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Выйти</a></li>
      </ul>
    </div>
  </div>

testruns/templates/testruns/index.html
{% extends 'base.html' %}
{% load django_jsonform %}


{% block content %}

      <section class="content">
            <div class="wrapper">
                <h1 class="content__title">Все запуски:</h1>
<!--                breadcrumps-->
                <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Home</li>
                    </ol>
                </nav>

                <div class="content__container">
                    <div class="content__data-box content__data-box_pos_up header_case">
                        <p class="content__data-box-subtitle">Последние запуски</p>
                        <div><button type="button" class="btn btn-dark" onclick="update_runs;">Обновить</button></div>
                    </div>


                </div>
                <div class="content__data-box content__data-box_pos_right feature-scenario">
                    <table class="table table-hover table-bordered">
                            <thead>
                            <tr>
                                <th scope="col">Билд</th>
                                <th scope="col">Статус</th>
                                <th scope="col">Автор</th>
                                <th scope="col">Дата</th>
                            </tr>
                            </thead>
                            <tbody>
                             {% for run in runs_list %}

                             {% if run.status == 'success' %}
                             <tr class="table-success position-relative">
                             {% elif run.status == 'killed' %}
                             <tr class="table-warning position-relative">
                             {% else %}
                             <tr class="table-danger position-relative">
                              {% endif %}

                             <td><b>{{ run.number }}</b><a class="pb-3 stretched-link" href="{{ run.get_link_in_drone }}"></a></td>
                             <td>{{ run.status }}</td>
                             <td>{{ run.autor_build }}</td>
                             <td>{{ run.date_run }}</td>


                            </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                      {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                <a href="/test-run?page={{ page_obj.previous_page_number }}"> << </a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>

                                {% if page_obj.has_next %}
                                <a href="/test-run?page={{ page_obj.next_page_number }}"> >> </a>
                                {% endif %}
                            </span>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>

{% endblock %}